-- Query 1------
select F_NAME , L_NAME
from EMPLOYEES
where ADDRESS LIKE '%Elgin,IL%' ;

SELECT * FROM EMPLOYEES;

--Query 
select F_NAME , L_NAME
from EMPLOYEES
where B_DATE LIKE '%197%';

--Q3
SELECT * FROM EMPLOYEES;
select F_NAME , L_NAME
from EMPLOYEES
where DEP_ID=5 AND SALARY IN (60000,70000);

--Q4A
SELECT F_NAME, L_NAME
FROM EMPLOYEES
ORDER BY DEP_ID;

--Q4B
SELECT F_NAME,L_NAME, DEP_ID FROM EMPLOYEES
 ORDER BY DEP_ID DESC, L_NAME DESC;

--Q5A
SELECT DEP_ID, COUNT(DEP_ID) FROM EMPLOYEES 
GROUP BY DEP_ID ;

--Q5B
SELECT DEP_ID, COUNT(DEP_ID), AVG(SALARY) 
FROM EMPLOYEES GROUP BY DEP_ID;

--Q5C
SELECT DEP_ID, COUNT(DEP_ID) AS "NUM_EMPLOYEES", 
AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES GROUP BY DEP_ID;

--Q5D
SELECT DEP_ID, COUNT(DEP_ID) AS "NUM_EMPLOYEES", 
AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES GROUP BY DEP_ID ORDER BY AVG(SALARY);

--Q5E
SELECT DEP_ID, COUNT(DEP_ID) AS "NUM_EMPLOYEES", 
AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES GROUP BY DEP_ID 
HAVING COUNT(DEP_ID)<4 ORDER BY AVG(SALARY);

--Q6
select D.DEP_NAME , E.F_NAME, E.L_NAME
from EMPLOYEES as E, DEPARTMENTS as D
where E.DEP_ID = D.DEPT_ID_DEP
order by D.DEP_NAME, E.L_NAME desc ;
 